version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"

  server:
    image: server-img
    build:
      context: ./Eureka_Server

    ports:
      - "8761:8761"

  gateway:
    image : gateway-img
    build:
      context: ./GateWay
    ports:
      - "8888:8888"

  client:
    image: client-img
    build:
      context: ./Client
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientServiceDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=  --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

  car:
    image: car-img
    build:
      context: ./Voiture
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carServiceDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=  --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD:
    ports:
      - "8081:80"
